# Generated by Django 4.0 on 2021-12-21 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SamplePersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('samplepersonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.samplepersonmodel')),
                ('job_object', models.TextField()),
            ],
            bases=('applications.samplepersonmodel',),
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('samplepersonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.samplepersonmodel')),
                ('job', models.TextField(default='unemployeed')),
            ],
            bases=('applications.samplepersonmodel',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('samplepersonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.samplepersonmodel')),
            ],
            bases=('applications.samplepersonmodel',),
        ),
        migrations.CreateModel(
            name='SuperVisor',
            fields=[
                ('samplepersonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.samplepersonmodel')),
            ],
            bases=('applications.samplepersonmodel',),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('headline', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.citizen')),
            ],
        ),
    ]
